### PR TITLE
GetbyName case insensitive #5

### PR DESCRIPTION
**Pull request by esakkiraja-k**
Hi,
I have a fix for GetbyName case insensitive issue. can anyone review the change and merge it. please let me know when I can see these changes in nuget repository.

### CODE REVIEW

**Comment by esakkiraja-k** [comment]
@abuassar 
@yuriy-nelipovich ,
can anyone of you please approve and merge the changes. I need the nuget with this changes badly.

thanks,
Raja

**Comment by nullptre** [comment]
Hi Raja, 
Can you make it configurable? to avoid a breaking change. Otherwise I'm going to review it and do that change. Estimated time: next week.

Regards,
Yuriy

**Comment by esakkiraja-k** [comment]
Thanks Yuriy.by Next week if you could add it  I am happy .Appreciate your help. didn't get time to add tests. I will add it later and contribute more if i get time. nice work.

**Comment by esakkiraja-k** [comment]
@yuriy-nelipovich ,could you please merge my changes.

**Pull request closed without merging**
